version: '3.8'

services:
  webp-img:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webp-img
    ports:
      - "8080:8080"
    volumes:
      # 将上传的图片存储在宿主机上，以便持久化
      - ./uploads:/app/uploads
    environment:
      # 应用配置
      - WEBP_SERVER_PORT=8080
      - WEBP_QUALITY=80
      # 目录配置
      - WEBP_UPLOAD_DIR=/app/uploads
      - WEBP_TEMPLATE_DIR=/app/templates
      - WEBP_PICS_DIR=/app/uploads/pics
      - WEBP_WEBP_DIR=/app/uploads/webp
      # 安全配置 - 生产环境中应使用更安全的密码和密钥
      - WEBP_ACCESS_PASSWORD=webpimg
      - WEBP_UPLOAD_PASSWORD=webpimg
      - WEBP_JWT_SECRET=webpimg-secure-jwt-secret-key
      - WEBP_JWT_EXPIRATION_HOURS=24
      - WEBP_MAX_LOGIN_ATTEMPTS=5
      - WEBP_LOCKOUT_MINUTES=15
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/login"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s