version: '3.8'

services:
  webp-img:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webp-img
    ports:
      - "8080:8080"
    volumes:
      # 将上传的图片存储在宿主机上，以便持久化
      - ./uploads:/app/uploads
    environment:
      - WEBP_SERVER_PORT=8080
      - WEBP_QUALITY=80
      # 这些路径是容器内部的路径，不需要更改
      - WEBP_UPLOAD_DIR=/app/uploads
      - WEBP_TEMPLATE_DIR=/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s